package auto

import (
	"encoding/json"
	"github.com/gin-gonic/gin"
	"net/http"
	pkg_api "wecome-ipad/util/http"
)

type AutoGenerated struct {
	Code int `json:"code"`
	Data struct {
		WxID         string `json:"wx_id"`
		HeadImageURL string `json:"head_image_url"`
		NickName     string `json:"nick_name"`
		Status       string `json:"status"`
	} `json:"data"`
}

func Auto(c *gin.Context) {

	apiHandler := pkg_api.MacApi{Authorization: c.GetHeader("Authorization")}
	ret := apiHandler.GetJson("/login/auto", map[string]string{})

	respAuto := &AutoGenerated{}
	_ = json.Unmarshal([]byte(ret), respAuto)
	c.JSON(http.StatusOK, respAuto)
}
